version: '3.8'

services:
  postgres_test:
    image: postgres:16-alpine
    container_name: auth_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db_test
    ports:
      - "5439:5432"
    networks:
      - auth_test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis_test:
    image: redis:7-alpine
    container_name: auth_redis_test
    ports:
      - "6389:6379"
    networks:
      - auth_test_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  auth_test_network:
    driver: bridge
