name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PNPM
        uses: pnpm/action-setup@fe6cd3402a4151622294165bc104aaed75860b3e
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@39370e3973fc2f0429ac512a68f3775a63547315
        with:
          node-version: '24'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Application
        run: pnpm run build

      - name: Prune development dependencies
        run: pnpm prune --production

      - name: Copy files to EC2 via SCP
        uses: appleboy/scp-action@4926176595507ff1990c7fbe8b555d494883fb8b
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'dist/,node_modules/,package.json,pnpm-lock.yaml'
          target: '/home/ubuntu/var/www/auth-backend'

      - name: Restart PM2 on EC2
        uses: appleboy/ssh-action@7e32234c4d267d716496f3bb9ec4fea6a20e4b95
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/var/www/auth-backend
            /usr/bin/pm2 restart auth-backend-app || /usr/bin/pm2 start dist/main.js --name "auth-backend-app"
