name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PNPM
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Application
        run: pnpm run build

      - name: Prune development dependencies
        run: pnpm prune --production

      - name: Copy files to EC2 via SCP
        uses: appleboy/scp-action@5bb815ae7f76baf13e1646dc59b8239beeb6ed57 # master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'dist/,node_modules/,package.json,pnpm-lock.yaml'
          target: '/home/ubuntu/var/www/auth-backend'

      - name: Restart PM2 on EC2
        uses: appleboy/ssh-action@068c0c7a4e59a5ae12fb7cb454b05735d830c82b # master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/var/www/auth-backend

            # 1. Load environment profiles
            [ -f ~/.profile ] && . ~/.profile
            [ -f ~/.bashrc ] && . ~/.bashrc

            # 2. Load NVM
            export NVM_DIR="$HOME/.nvm"
            if [ -s "$NVM_DIR/nvm.sh" ]; then
              \. "$NVM_DIR/nvm.sh"
              nvm use default || nvm use node || true
            fi

            export PATH="$PATH:$HOME/.npm-global/bin"

            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing global prefix..."
              npm install pm2 -g --prefix ~/.npm-global
              export PATH="$HOME/.npm-global/bin:$PATH"
            fi

            echo "Installing production dependencies..."
            npx pnpm install --prod --frozen-lockfile

            if pm2 describe auth-backend-app &> /dev/null; then
              echo "Application exists, restarting..."
              pm2 restart auth-backend-app
            else
              echo "Application does not exist, starting for the first time..."
              pm2 start dist/main.js --name "auth-backend-app"
            fi
